[package]
org = "xlibb"
name = "docparser"
version = "@toml.version@"
authors = ["xlibb"]
keywords = ["docparser", "documentation", "parser"]
repository = "https://github.com/AzeemMuzammil/module-docparser"
license = ["Apache-2.0"]
distribution = "2201.12.0"
icon = "icon.png"

[[platform.java21.dependency]]
groupId = "io.xlibb.docparser"
artifactId = "docparser-native"
version = "@toml.version@"
path = "../native/build/libs/docparser-native-@project.version@.jar"
