[package]
org = "xlibb"
name = "docparser"
version = "0.1.0"
authors = ["xlibb"]
keywords = ["docparser", "documentation", "parser"]
repository = "https://github.com/AzeemMuzammil/module-docparser"
license = ["Apache-2.0"]
distribution = "2201.12.0"
icon = "icon.png"

[[platform.java21.dependency]]
groupId = "io.xlibb.docparser"
artifactId = "docparser-native"
version = "0.1.0"
path = "../native/build/libs/docparser-native-0.1.0-SNAPSHOT.jar"
